### ISSUE TITLE
Generated AU3 Scripts Do Not Call Generated Functions

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/sheepl#1]
When running `python3 sheepl.py --interactive` and creating a new .au3 file, the AutoIT3 script appears to be incomplete.

Download script: [test.au3.txt](https://github.com/SpiderLabs/sheepl/files/2679815/test.au3.txt)
The script generated by sheepl is as below:

>#include <Word.au3>
>#include <IE.au3>
>#include <Array.au3>
>Opt("SendKeyDelay", 70)
>
>; define global task list
>Global $aTasks[5] = ['IE_4', 'TeaBreak_1', 'CMD_2', '0_Teabreak', 'Powershell_0'] 
>; creates Sleep Times array
>Global $aSleepTimes[5] = ['106323', '104532', '52805', '24750', '11590']
>; copies original array just encase the task list borks
>$aRandTasks = $aTasks
>        
>; < ----------------------------------- >
>; <          IE Interaction
>; < ----------------------------------- >
>
>
>
>Func IE_4()
>
>    Local $oIE = _IECreate("google.com",1,1,1)
>    Sleep(2000)
>    ;WinWaitActive("Windows Internet Explorer")
>    ;SendKeepActive("Windows Internet Explorer")
>    ;WinSetState("Windows Internet Explorer","",@SW_MAXIMIZE)
>    ; hardcoded sleep for now
>    ; will convert to AutoIT random
>    ; this is also where the IE interaction such as logging in etc will happen,
>    ; spawning new tabs etc
>    ; prob need a call out function to trigger a subroutine
>    Sleep(20000)
>    Send("!{F4}")
>
>        
>
>    SendKeepActive("")
>    _IEQuit($oIE)
>
>    EndFunc
>        
>; < ----------------------------------- >
>; <             Tea Break
>; < ----------------------------------- >
>
>; Nothing to do here but have a cuppa, it's a placeholder for a tea break
>; creates an entry in the task list to then take a random slice of the
>; timeslot which results in a random sleep action
>        
>; < ----------------------------------- >
>; <          CMD Interaction
>; < ----------------------------------- >
>
>
>Func CMD_2()
>
>
>    Send("#r")
>    ; Wait 10 seconds for the Run dialogue window to appear.
>    WinWaitActive("Run", "", 10)
>    Send("cmd{ENTER}")
>    WinWaitActive("[CLASS:ConsoleWindowClass]", "", 10)
>    SendKeepActive("[CLASS:ConsoleWindowClass]")
>
>    
>    Send("hostname{ENTER}")
>    sleep(10324)
>    Send("whoami{ENTER}")
>    sleep(18192)
>    Send("ping 8.8.8.8{ENTER}")
>    sleep(2742)
>
>
>    Send('exit{ENTER}')
>    SendKeepActive("")
>
>    EndFunc
>        
>; < ----------------------------------- >
>; <             Tea Break
>; < ----------------------------------- >
>
>; Nothing to do here but have a cuppa, it's a placeholder for a tea break
>; creates an entry in the task list to then take a random slice of the
>; timeslot which results in a random sleep action
>        
>    ; < ----------------------------------- >
>    ; <       PowerShell Interaction
>    ; < ----------------------------------- >
>
>    
>
>Func PowerShell_0()
>        Send("#r")
>        ; Wait 10 seconds for the Run dialogue window to appear.
>        WinWaitActive("Run", "", 10)
>        Send("powershell{ENTER}")
>        WinWaitActive("Windows PowerShell", "", 10)
>        SendKeepActive("Windows PowerShell")
>       
>    Send("gwmi win32_service{ENTER}")
>    sleep(6995)
>    Send("$psversiontable{ENTER}")
>    sleep(5058)
>    Send("exit{ENTER}")
>    sleep(4298)
>
>    sleep(2000)
>    Send("exit{ENTER}")
>    EndFunc

As you can see from the above, an array is created of all the functions that Sheepl has generated and a second array of sleep times however, these do not appear to be used or called anywhere (except for the case of the backup variable for the $aTasks array...)

When passing this script to Au3Check, it passes with no errors or warnings however, when trying to execute the script with AutoIT3, it appears to process the script but, as none of the functions within it are ever actually called, nothing happens.

Additionally, within the $aTasks array there are values for teabreak functions which do not appear to exist within the script.

**Comment by lorentzenman** [comment]
First of all, thank you for taking the time to raise an issue as you are the first.

So looking at your code, the while part is missing and after a quick test this is down to the loop being set to 'no' in the interactive console.
I always set mine to loop and it looks like I have omitted the logic for when someone selects no looping.
The issue is at line 255 inside the sheepl object

`if self.loop == True:`

but there is no condition for no loop. I will fix this and push a new code base tomorrow.

Below is my output when looping is set to true, and as you can see, the arrays are indeed used. Probably don't really need to clone the array to be honest, and I have been working on a major rewrite for 0.3 so I will catch the redundant AutoIT arrays in that version.

```
#include <Word.au3>
#include <IE.au3>
#include <Array.au3>
Opt("SendKeyDelay", 40)

; define global task list
Global $aTasks[6] = ['0_Teabreak', 'TeaBreak_0', 'CMD_1', 'Powershell_2', 'TeaBreak_3', 'IE_5']
; creates Sleep Times array
Global $aSleepTimes[6] = ['13492', '156577', '111726', '124016', '139431', '54758']
; copies original array just encase the task list borks
$aRandTasks = $aTasks

; this is the loop that works if they have loop switch in sheepl set
; this is the master loop - will got forever
While 1
   ; this needs to grab the last shuffled sleep entry from tasks
    _ArrayShuffle($aRandTasks)
        ; clone the sleep array into this while loop
        $aRandSleepTimes = $aSleepTimes
        ; shuffle this array so it's unique everytime
        _ArrayShuffle($aRandSleepTimes)

   ConsoleWrite("[!] Going round the loop" & @CRLF)
   For $i In $aRandTasks
      ; start with a sleep Value
      ; pops the last shuffled value from the sleep array and assigns
      Local $vSleepTime =_ArrayPop($aRandSleepTimes)
      ConsoleWrite("[!] I will now sleep for : " & $vSleepTime & @CRLF)
      ; Sets the sleep time
      Sleep($vSleepTime)
          ;ConsoleWrite($i & @CRLF)
          ; gets the current function from the shuffled array
          $curfunc = ($i & @CRLF)
          ConsoleWrite($curfunc)
          ; call the function from the shuffled array
          ; the magic call
          Call($i)

   Next

WEnd

; < ----------------------------------- >
; <             Tea Break
; < ----------------------------------- >

; Nothing to do here but have a cuppa, it's a placeholder for a tea break
; creates an entry in the task list to then take a random slice of the
; timeslot which results in a random sleep action

; < ----------------------------------- >
; <             Tea Break
; < ----------------------------------- >

; Nothing to do here but have a cuppa, it's a placeholder for a tea break
; creates an entry in the task list to then take a random slice of the
; timeslot which results in a random sleep action

; < ----------------------------------- >
; <          CMD Interaction
; < ----------------------------------- >


Func CMD_1()

    Send("#r")
    ; Wait 10 seconds for the Run dialogue window to appear.
    WinWaitActive("Run", "", 10)
    Send("cmd{ENTER}")
    WinWaitActive("[CLASS:ConsoleWindowClass]", "", 10)
    SendKeepActive("[CLASS:ConsoleWindowClass]")


    Send("hostname{ENTER}")
    sleep(4617)
    Send("ping 8.8.8.8{ENTER}")
    sleep(6303)
    Send("whoami{ENTER}")
    sleep(11425)


    Send('exit{ENTER}')
    SendKeepActive("")

    EndFunc

    ; < ----------------------------------- >
    ; <       PowerShell Interaction
    ; < ----------------------------------- >



Func PowerShell_2()
        Send("#r")
        ; Wait 10 seconds for the Run dialogue window to appear.
        WinWaitActive("Run", "", 10)
        Send("powershell{ENTER}")
        WinWaitActive("Windows PowerShell", "", 10)
        SendKeepActive("Windows PowerShell")


    Send("gwmi win32_service{ENTER}")
    sleep(10964)
    Send("$psversiontable{ENTER}")
    sleep(6949)

        sleep(2000)
        Send("exit{ENTER}")
        EndFunc


; < ----------------------------------- >
; <             Tea Break
; < ----------------------------------- >

; Nothing to do here but have a cuppa, it's a placeholder for a tea break
; creates an entry in the task list to then take a random slice of the
; timeslot which results in a random sleep action

; < ----------------------------------- >
; <          IE Interaction
; < ----------------------------------- >



Func IE_5()

    Local $oIE = _IECreate("http://www.google.com",1,1,1)
    Sleep(2000)
    ;WinWaitActive("Windows Internet Explorer")
    ;SendKeepActive("Windows Internet Explorer")
    ;WinSetState("Windows Internet Explorer","",@SW_MAXIMIZE)
    ; hardcoded sleep for now
    ; will convert to AutoIT random
    ; this is also where the IE interaction such as logging in etc will happen,
    ; spawning new tabs etc
    ; prob need a call out function to trigger a subroutine
    Sleep(20000)
    Send("!{F4}")



    SendKeepActive("")
    _IEQuit($oIE)

    EndFunc```

**Comment by lorentzenman** [comment]
Regarding the teabreak functions, that is the correct behaviour, they only serve to assign what is essentially a 'null' task, but the benefit is that they take a portion of time relative to the amount of tasks. As an example you could have one cmd task and 4 teabreaks, the total length is 5 tasks, so the time gets split up according to this total task length which is useful, especially when looping as each time through the loop will shuffle the task list and then sleep times.
Without looping, they get baked in the order you supplied them and exit when the total time is completed.

**Comment by ghost** [comment]
I noticed that there hasn't been an update to this in a while so, I've forked the repo and started to debug and re-write some of the code.

Even when I produce an au3 file with looping enabled, the script does not function (it runs but, doesn't actually do anything.)

I believe the section of code that is causing the problem is:

```
; define global task list
Global $aTasks[5] = ['0_Teabreak', 'CMD_0', 'IE_2', 'TeaBreak_2', 'IE_4']
; creates Sleep Times array
Global $aSleepTimes[5] = ['591511', '295716', '434124', '1221430', '1057219']
; copies original array just encase the task list borks
$aRandTasks = $aTasks

; this needs to grab the last shuffled sleep entry from tasks
 _ArrayShuffle($aRandTasks)
 ; clone the sleep array into this while loop
 $aRandSleepTimes = $aSleepTimes
 ; shuffle this array so it's unique everytime
 _ArrayShuffle($aRandSleepTimes)

ConsoleWrite("[!] Going round the loop" & @CRLF)
For $i In $aRandTasks
   ; start with a sleep Value
   ; pops the last shuffled value from the sleep array and assigns
   Local $vSleepTime =_ArrayPop($aRandSleepTimes)
   ConsoleWrite("[!] I will now sleep for : " & $vSleepTime & @CRLF)
   ; Sets the sleep time
   Sleep($vSleepTime)
   ;ConsoleWrite($i & @CRLF)
   ; gets the current function from the shuffled array
   $curfunc = ($i & @CRLF)
   ConsoleWrite($curfunc)
   ; call the function from the shuffled array
   ; the magic call
   Call($i)
Next
```
None of the functions that are generated appear to actually be getting called.
I removed the above snippet of code from the au3 script and instead called each of the functions by name `cmd_0()`, etc and the script ran fine (throws errors when it encounters the non-existent teabreak functions, ofc so, no calls to those.)

In my fork, I have already implemented an `else` clause to the `if self.loop == true` statement however, until we resolve the above it appears that the au3 scripts generated by this application aren't going to work.

Below are the two au3 files that Sheepl has generated both with the looping mechanism and without.

## Files
[noloop.au3.txt](https://github.com/SpiderLabs/sheepl/files/2742686/noloop.au3.txt)
[loop.au3.txt](https://github.com/SpiderLabs/sheepl/files/2742688/loop.au3.txt)

**Comment by lorentzenman** [comment]
Sorry, for the delay, there were some permission changes that prevented me from pushing. I have now got access and managed to push the fix i sorted 16 days ago.
Seems like we are both on the same page, so thanks for your interest.

I have refactored a lot of this for 0.3 which is a essentially a rewrite.
