### ISSUE TITLE
[Putty Module] o at the beginning of the username

### ISSUE THREAD

**Issue by michaelb** [SpiderLabs/sheepl#6]
Hey! I have been using sheepl for test purposes, but I found that the Putty Module would not work because of a very strange "bug"

Any username specified in the interactive prompt end up being typed in Putty as "o"+<username>, eg: 
[in interactive sheepl prompt]
-> username: mika
etc.....
[in putty shell]
-> login: omika
-> password: ####
Connection to omika@server failed
(obviously, as this server as no "omika" user)

I found the culprit in the putty module .py file line 448, removing it solved the issue, however as I can't figure out what the "Send(!o)" (and "send(!n)") do I will not submit a pull request

(in W10 virtual machine, up-to-date at 09 August 2019. Terminal used for sheepl interaction: cmder)

**Comment by lorentzenman** [comment]
Thanks for the issue submission. Apologies for not picking this up sooner. Those are keyboard combinations, like ALT + o. I will check the module and replicate the issue.

**Comment by lorentzenman** [comment]
So when testing this, i managed to get the same condition once. It only seemed to appear after the first loop and appeared to be a race condition. The Send("!o") is sending the Alt + o combination to open the putty window. However, this is redundant code as the previous line sends an 'enter' after adding in the computer target.

I have now removed the Send("!o") line and pushed this fix.

Thanks for the bug report.

**Comment by michaelb** [comment]
You are welcome :-)
